// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMn7FlDnk4fg1mOVuGrSct44qEM7ONHYA',
    appId: '1:990024272519:web:ddf69d10120d22ccbd0622',
    messagingSenderId: '990024272519',
    projectId: 'our-smart-rental-system',
    authDomain: 'our-smart-rental-system.firebaseapp.com',
    storageBucket: 'our-smart-rental-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4_2NJRCyoKPezsxMoGWOlCNVH4tI-JS0',
    appId: '1:990024272519:android:b51b079e8e19370fbd0622',
    messagingSenderId: '990024272519',
    projectId: 'our-smart-rental-system',
    storageBucket: 'our-smart-rental-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbo7ZPDsWwxgk63gul0jyUrsTFpQaAQuE',
    appId: '1:990024272519:ios:2812aa2291cdeaeabd0622',
    messagingSenderId: '990024272519',
    projectId: 'our-smart-rental-system',
    storageBucket: 'our-smart-rental-system.firebasestorage.app',
    iosBundleId: 'com.example.smartRentalSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbo7ZPDsWwxgk63gul0jyUrsTFpQaAQuE',
    appId: '1:990024272519:ios:2812aa2291cdeaeabd0622',
    messagingSenderId: '990024272519',
    projectId: 'our-smart-rental-system',
    storageBucket: 'our-smart-rental-system.firebasestorage.app',
    iosBundleId: 'com.example.smartRentalSystem',
  );
}
